### ISSUE TITLE
no website in website section

### ISSUE THREAD

**Issue by sweta123761** [andoriyaprashant/DevDocsHub#1]
there is no website in your website section . you can assign that task to me

**Comment by andoriyaprashant** [comment]
Hello @sweta123761  the website pages are located in the templates folder of the Django project. You can contribute by working on the HTML files there. It seems there was a misunderstanding since the pages already exist in that folder

**Comment by andoriyaprashant** [comment]
> there is no website in your website section . you can assign that task to me

@sweta123761 If you want to make changes to the website, you can open a new issue and work on it
