### ISSUE TITLE
Feat:adding a new page to display all contributors✨

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [andoriyaprashant/DevDocsHub#100]
### Describe the feature

I want to add a seperate page to showcase all the contributors of this website.
@andoriyaprashant can you assign me this issue,

### Add ScreenShots

-

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by andoriyaprashant** [comment]
Hello @T-Rahul-prabhu-38 I dont think we need this 
Thank you
