### ISSUE TITLE
Feat: Adding social media username

### ISSUE THREAD

**Issue by Aazib-at-hub** [andoriyaprashant/DevDocsHub#101]
### Describe the feature

Will be adding social media handle beside social media icons.So, that if a person wants to follow later on he can remember the username.

### Add ScreenShots

![Screenshot from 2024-10-16 03-31-58](https://github.com/user-attachments/assets/6e9017a9-ea2f-4fc5-a65b-1ddaed1b20bb)
this is the current footer.will be arranging the social media icons in top-down manner and beside the social media icon will be adding their respective handles.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by thestuti** [comment]
assigned it to you!
