### ISSUE TITLE
creation of about and contact templates 

### ISSUE THREAD

**Issue by aditya07389** [andoriyaprashant/DevDocsHub#102]
hey @thestuti @andoriyaprashant 
I noticed that there is no about us page and contact us page 

i would like to work on this 
I have some experience in Django 

you can assign this task to me with labels : gssoc extd , hacktoberfest,level 3

Thankyou!

**Comment by thestuti** [comment]
sure.

**Comment by aditya07389** [comment]
Thankyou, ill raise the pr soon !
