### ISSUE TITLE
DOC: Updating the README file

### ISSUE THREAD

**Issue by Divija-Arora** [andoriyaprashant/DevDocsHub#115]
### What's wrong with the existing documentation

The README lacks visual appeal, like images demonstrating the application's interface.
It could use better organization, like a table of contents for easier navigation. Also, all technologies and libraries used in the project (e.g., Django, HTML, CSS, etc.) should be listed.
Specify the license under which the project is distributed since license information is missing.
A contact section for contributors at the end would be helpful. (I've attached the ss below, that is just a sample of how the structure could look like.). Also "hacktoberfest" tag is not there in About.
@thestuti @andoriyaprashant 
Can you assign me the issue, I would like to work over it.

### Add ScreenShots

![Screenshot (2720)](https://github.com/user-attachments/assets/58a4e33d-7077-4431-9d42-da252ec9e5a9)
![Screenshot (2721)](https://github.com/user-attachments/assets/39d4e49e-0692-40cb-a6aa-4bcedf0374c3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by thestuti** [comment]
assigned it to you!
