### ISSUE TITLE
Feat: Design and Add Logo to the Website

### ISSUE THREAD

**Issue by Swati-bs** [andoriyaprashant/DevDocsHub#119]
### Describe the feature

This feature involves designing a unique logo for the website and integrating it across key areas to enhance the site's visual identity and improve user recognition.

**Custom Logo Design:**

- [x] Create a new logo that reflects the brand’s core values and mission.
- [x] Ensure the design is adaptable for various formats (e.g., web, favicon, mobile).

**Integration:**

- [x] Add the logo to the header for prominent visibility on all pages.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/35ce6545-0e88-4ea8-b6a8-baffc03c9c02)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Hafsa-shoaib989** [comment]
@andoriyaprashant can you please assign this task to me?

**Comment by Swati-bs** [comment]
Can you please assign a level to Issue #144  ? The issue has already been fixed, and my changes have been successfully merged via PR #144 . However, the level hasn’t been assigned yet, and my name is not visible on the leaderboard. Please assign the appropriate level so my contribution is properly recognized.
