### ISSUE TITLE
DOC: Add repo_structure.txt for easy browsing and efficient file maintenance

### ISSUE THREAD

**Issue by Swati-bs** [andoriyaprashant/DevDocsHub#151]
### What's wrong with the existing documentation

The existing documentation lacks a clear and concise reference for the project’s folder and file structure, which can make it challenging for new contributors or team members to quickly navigate and maintain the project files. Adding a repo_structure.txt file would provide a simple, easily accessible overview of the project's organization, helping contributors understand the purpose of each directory and file within the repo. This addition would streamline the process of finding relevant files, improving overall project efficiency, and ensuring that the repository remains easy to manage as it grows.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/fb1d2635-1468-45f7-bce2-30ea98120f49)

The HTML templates are currently disorganized and not placed in the appropriate folders, making it harder to navigate, so reorganizing them and adding a repo_structure.txt for a clear overview would improve maintainability and make the project easier to work with.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by thestuti** [comment]
I don't think we need that
