### ISSUE TITLE
Enhance User Authentication and Data Security

### ISSUE THREAD

**Issue by Nayanpatel48** [andoriyaprashant/DevDocsHub#24]
Hi @andoriyaprashant ,

I'm interested in contributing to this project by **improving/adding user authentication and data security**.

I propose implementing:

```
Sign up a user (Email/Password)
Sign in a user
Sign out a user
Form Validation and Handle Errors
Handle User Authentication State
Email Verification
Forgot/Reset Password
Google Sign in
Facebook Sign in
Add, Get & Update Logged In User Data
Upload, Get & Update Logged In User Profile Picture.
```

I'm ready to discuss this further and contribute a pull request.

**Comment by Aditya-Mishra9670** [comment]
hi  @andoriyaprashant ,
I have contributed in user authentication and raised a pr , kindly check it .

**Comment by andoriyaprashant** [comment]
Hello @Aditya-Mishra9670 @Nayanpatel48   I had mentioned earlier #6  that I do not want to add a login or signup feature to this website because I want it to remain an open site where people can access the documentation and use the website.

**Comment by andoriyaprashant** [comment]
And @Nayanpatel48  please don't open a duplicate issue; I have already closed the same issue before
