### ISSUE TITLE
✨fixing CSS files

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [andoriyaprashant/DevDocsHub#42]
inline CSS slows the overall webpage during loading phase , if u can assign me this ill quickly fix the problem and fix it.
@andoriyaprashant  can you please consider this.

**Comment by MAYANK12SHARMA** [comment]
@andoriyaprashant sir I have fix that issue. Please check it out.

**Comment by T-Rahul-prabhu-38** [comment]
@MAYANK12SHARMA  mayank bhai im not sure thats how it works , u need to get assigned only then u can raise a PR , i was assigned this and i have already raised a PR.

**Comment by MAYANK12SHARMA** [comment]
@T-Rahul-prabhu-38  bhai, Anyone can raise the PR. It will not add  to the actual codebase until and Unless @andoriyaprashant  sir confirm it.

**Comment by T-Rahul-prabhu-38** [comment]
bhai did u attend the Gssoc live vids where they explained the rules.

**Comment by T-Rahul-prabhu-38** [comment]
<img width="336" alt="Screenshot 2024-10-07 at 12 35 20 AM" src="https://github.com/user-attachments/assets/fbca5d97-93c0-42dc-99f7-757448b9019a">

only after your name is registerd under assigned u can start.

**Comment by MAYANK12SHARMA** [comment]
Sorry I didn't see it. If it is then sir will consider yours not mine and I will delete my pull request and please mention the time line of that part of youtube video

**Comment by T-Rahul-prabhu-38** [comment]
no worries we are all new here , im not sure about the timeline but ive done multiple PR's and they accepted only when they assigned me the issue.
