### ISSUE TITLE
Replacing dark mode text with dark mode icon with some hover effect 

### ISSUE THREAD

**Issue by PATILYASHH** [andoriyaprashant/DevDocsHub#45]
I will update the appearance of dark mode / light mode button with some hover effect and animations using bootstrap 

![image](https://github.com/user-attachments/assets/18b03102-befa-4b0b-9ce7-226703e5348d)

**Comment by PATILYASHH** [comment]
I did PR please check it

**Comment by PATILYASHH** [comment]
@andoriyaprashant sir please check my PR and review the PR

**Comment by akshatjaiin** [comment]
looking for some web related projects to work on i love to work on this issue under gssoc 24 extnd. can you assign that to me ?
