### ISSUE TITLE
Enhancing website name text appearance 

### ISSUE THREAD

**Issue by PATILYASHH** [andoriyaprashant/DevDocsHub#50]
## website name Text appearance is normal , I will  add some animations and hover effect to it.

**Screenshot**

- Before 
![image](https://github.com/user-attachments/assets/37e862ca-8062-41da-979d-3f1009eac3f8)

- After 

https://github.com/user-attachments/assets/ffa5d996-d7c0-4cab-91b8-50d6cdd7ad77

---

PR no : #

**Comment by andoriyaprashant** [comment]
Hello @PATILYASHH 
I dont think we need this 
Thank you
