### ISSUE TITLE
Improve Footer by Adding Social Media Links, Address, and Additional Information

### ISSUE THREAD

**Issue by MAYANK12SHARMA** [andoriyaprashant/DevDocsHub#61]
**Description:**
Currently, the footer contains minimal information:
![image](https://github.com/user-attachments/assets/93c8e239-c256-47d6-bf9c-076b78b3763f)

While this is functional, a more comprehensive footer can significantly enhance user engagement and provide important contact information. I propose improving the footer by adding the following elements:

**Proposed Additions:**
**Social Media Links:**

Add icons/links for social media platforms like:
Twitter
LinkedIn
GitHub
Facebook (if applicable)
These will help users easily connect with DevDocsHub on various platforms.
**Company Address:**

Include a physical address or a general location (if applicable) to provide more legitimacy and contact information.
**Contact Email:**

Add a support or general inquiry email to allow users to reach out for questions or issues.
**Quick Links:**

Add useful links such as:
About Us
Careers
Blog or News (if available)
Newsletter Signup (Optional):

Provide an option for users to sign up for a newsletter to keep them updated with new features, blog posts, or other updates.
Copyright Year:

Ensure the copyright year is automatically updated so that it stays current.
**Benefits:**
Improved User Engagement: By providing social media links, users can easily follow and engage with the community.
Professionalism: Adding contact details and social media links enhances the overall professionalism of the website.
Better Accessibility: Offering quick links to important sections like "About Us" or "Careers" helps users navigate the site more easily.
**Request:**
Could we consider implementing this improved footer design? I'd be happy to contribute to this feature if assigned!

**Comment by andoriyaprashant** [comment]
Hello @MAYANK12SHARMA 
I don’t think we need this right now; maybe we’ll need it in the future because we don’t have a social media platform for this website
