### ISSUE TITLE
Feat: Add Viewing Password feature 

### ISSUE THREAD

**Issue by akanksha1055** [andoriyaprashant/DevDocsHub#75]
### Describe the feature

I will add eye icon in password with password viewing option
right now we cant see what password is entered

### Add ScreenShots

![image](https://github.com/user-attachments/assets/bf523056-4383-41f3-8b39-f970c08e97d8)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by thestuti** [comment]
you may work on this!

**Comment by akanksha1055** [comment]
i would also add icons near the input field that will make the page more interactive ....could u please assign level 2 label
