### ISSUE TITLE
Feat:Search Filter Not Working for Resources made it dynamically

### ISSUE THREAD

**Issue by punishermortal** [andoriyaprashant/DevDocsHub#79]
### Describe the feature

**Description:**

The search filter functionality on **DevDocsHub** currently does not work as expected when users try to search for specific programming resources. I would like to propose an enhancement where the search feature is updated and optimized to allow users to easily find resources based on keywords like  **language, doc_title, or doc_url.**

**Proposed Solution**:

 **1.**   Implement a search functionality that allows users to search for resources using relevant filters (**language, doc_title, or doc_url.**).
  **2.**  Ensure that the search results are accurate and display relevant resources based on user input.
  
  
  This feature will improve the usability of the platform, allowing users to quickly locate the programming resources they need.

### Add ScreenShots

![Screenshot from 2024-10-10 00-54-04](https://github.com/user-attachments/assets/c646e957-ee09-4895-86af-ca710aab1b15)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by punishermortal** [comment]
in which levels this features lies? @andoriyaprashant

**Comment by akshatjaiin** [comment]
under gssoc 24 extnd. can you assign that to me ?
